jacksund/simmate

CHANGELOG.md, src/simmate/calculators/deepmd/inputs/type_and_set.py, src/simmate/calculators/vasp/workflows/dynamics.py, src/simmate/calculators/vasp/workflows/nudged_elastic_band/all_paths.py, src/simmate/calculators/vasp/workflows/nudged_elastic_band/from_images.py, src/simmate/calculators/vasp/workflows/relaxation/_to_do/staged_use_same_dir.py, src/simmate/command_line/run_server.py, src/simmate/configuration/dask/connect_to_database.py, src/simmate/configuration/django/database.py, src/simmate/database/prototypes/webscraping/aflow.py, src/simmate/database/third_parties/for_providers/_todo/mpds.py, src/simmate/toolkit/creators/structure/prototypes/exact_match.py, src/simmate/toolkit/creators/structure/prototypes/ordered.py, src/simmate/toolkit/structure_prediction/evolution/search_engine.py, src/simmate/utilities/__init__.py, src/simmate/utilities/files.py, src/simmate/utilities/test/test_files.py, src/simmate/website/workflows/forms.py, src/simmate/website/workflows/test/test_workflows_views.py, src/simmate/workflow_engine/__init__.py, src/simmate/workflow_engine/common_tasks/load_input_and_register.py, src/simmate/workflow_engine/supervised_staged_shell_task.py, src/simmate/workflow_engine/utilities.py, src/simmate/workflows/test/test_workflows_utilities.py
- resolves #76 
- resolves #101
=> Enhance file management bt errors and workflow runs

src/simmate/workflow_engine/test/test_workflow.py, src/simmate/workflow_engine/workflow.py
=> sort parameter_names

src/simmate/calculators/vasp/database/relaxation.py, src/simmate/calculators/vasp/inputs/incar.py, src/simmate/calculators/vasp/tasks/dynamics/__init__.py, src/simmate/calculators/vasp/tasks/dynamics/materials_virtual_lab_npt.py, src/simmate/calculators/vasp/tasks/nudged_elastic_band/__init__.py, src/simmate/calculators/vasp/tasks/nudged_elastic_band/materials_virtual_lab_ci.py, src/simmate/calculators/vasp/tasks/nudged_elastic_band/mit.py, src/simmate/calculators/vasp/tasks/relaxation/__init__.py, src/simmate/calculators/vasp/tasks/relaxation/materials_virtual_lab_endpoint.py, src/simmate/calculators/vasp/tasks/static_energy/materials_project.py, src/simmate/calculators/vasp/tasks/static_energy/neb_endpoint.py, src/simmate/calculators/vasp/tasks/test/test_pymatgen_sets.py, src/simmate/calculators/vasp/workflows/nudged_elastic_band/all_paths.py, src/simmate/calculators/vasp/workflows/nudged_elastic_band/from_endpoints.py, src/simmate/calculators/vasp/workflows/nudged_elastic_band/from_images.py, src/simmate/calculators/vasp/workflows/nudged_elastic_band/single_path.py, src/simmate/calculators/vasp/workflows/relaxation/neb_endpoint.py, src/simmate/database/workflow_results/__init__.py, tutorials/01_Installation.md
=> continue adding pymatgen sets

.github/workflows/lint-and-test.yml, CHANGELOG.md, setup.py, tutorials/Guides_for_contributors/README.md, tutorials/Guides_for_contributors/environment.yaml
=> update CI w. pytest<7.1 and conda action

CHANGELOG.md, src/simmate/calculators/vasp/configuration.md
adding guide from @scott-materials for future reference
=> :books: add installation guide for vasp

pyproject.toml, src/simmate/calculators/vasp/workflows/diffusion/test/test_all_paths.py, src/simmate/calculators/vasp/workflows/electronic_structure/matproj_full.py, src/simmate/calculators/vasp/workflows/relaxation/staged.py, src/simmate/database/base_data_types/base.py, src/simmate/database/base_data_types/relaxation.py, src/simmate/database/third_parties/materials_project.py, src/simmate/toolkit/structure_prediction/evolution/database.py, src/simmate/toolkit/structure_prediction/evolution/search_engine.py, src/simmate/toolkit/validators/fingerprint/pcrystalnn.py, src/simmate/utilities/__init__.py, src/simmate/utilities/async_wrapper.py, src/simmate/utilities/other.py, src/simmate/workflow_engine/test/test_supervised_staged_shell_task.py, src/simmate/workflow_engine/test/test_workflow.py, src/simmate/workflow_engine/workflow.py, src/simmate/workflows/test/test_all_workflow_runs.py
=> :gorilla: refactor evo search alg

CHANGELOG.md, pyproject.toml, src/simmate/calculators/vasp/workflows/customized.py, src/simmate/calculators/vasp/workflows/diffusion/neb_all_paths.py, src/simmate/calculators/vasp/workflows/diffusion/neb_from_endpoints.py, src/simmate/calculators/vasp/workflows/diffusion/neb_from_images.py, src/simmate/calculators/vasp/workflows/diffusion/neb_single_path.py, src/simmate/calculators/vasp/workflows/dynamics.py, src/simmate/calculators/vasp/workflows/electronic_structure/matproj_full.py, src/simmate/calculators/vasp/workflows/population_analysis/badelf.py, src/simmate/calculators/vasp/workflows/relaxation/staged.py, src/simmate/workflow_engine/workflow.py
=> 🦋 fix handling of prefect futures

CHANGELOG.md, src/simmate/calculators/vasp/workflows/relaxation/staged.py, src/simmate/configuration/django/setup.py, src/simmate/database/workflow_results/__init__.py, src/simmate/toolkit/creators/structure/base.py, src/simmate/toolkit/structure_prediction/evolution/database/__init__.py, src/simmate/toolkit/structure_prediction/evolution/database/evolutionary_search.py, src/simmate/toolkit/structure_prediction/evolution/selectors.py, src/simmate/toolkit/structure_prediction/evolution/workflows/fixed_composition.py, src/simmate/toolkit/structure_prediction/evolution/workflows/new_individual.py, src/simmate/toolkit/transformations/base.py, src/simmate/website/workflows/test/test_workflows_views.py, src/simmate/workflow_engine/workflow.py
=> :shell: add output files to evo search

.github/workflows/lint-and-test.yml, CHANGELOG.md, pyproject.toml, src/simmate/configuration/dask/setup_cluster.py, src/simmate/toolkit/symmetry/webscraper/aflow.py, src/simmate/toolkit/symmetry/webscraper/bilbao_wyckoff.py, src/simmate/toolkit/symmetry/webscraper/itc_datascrape.py, src/simmate/utilities/__init__.py, src/simmate/utilities/async.py, src/simmate/workflow_engine/execution_prefect/workflow.py, tutorials/Guides_for_contributors/environment.yaml
=> :spider: update dependencies

pyproject.toml, tutorials/Guides_for_contributors/environment.yaml
=> ❄️ fix pytest on windows

CHANGELOG.md, docs/full_guides/workflows/creating_new_workflows.md, src/simmate/workflows/test/test_workflows_utilities.py, src/simmate/workflows/utilities.py
=> :rose: update workflow docs and allow custom yaml

.github/ISSUE_TEMPLATE/1-bug_report.yaml, .github/ISSUE_TEMPLATE/2-feature_request.yaml, CHANGELOG.md, pyproject.toml, src/simmate/command_line/database.py, src/simmate/database/third_parties/for_providers/materials_project.py, src/simmate/database/third_parties/materials_project.py
=> :trophy: update matproj data

CHANGELOG.md, src/simmate/toolkit/structure_prediction/evolution/database/evolutionary_search.py
=> :bee: fix resource busy and write_summary errors 

CHANGELOG.md, src/simmate/calculators/vasp/workflows/diffusion/neb_from_images_base.py, src/simmate/calculators/vasp/workflows/diffusion/neb_from_images_mit.py, src/simmate/calculators/vasp/workflows/test/test_nudged_elastic_band.py
- fixes #248
- fixes NEB hints for `workup` failure due to missing start/end image foldernames
@becca9835
=> :trumpet: fix neb bugs

.github/environment.yaml, CHANGELOG.md, docs/full_guides/workflows/creating_new_workflows.md, docs/getting_started/custom_workflows/update_an_existing_workflow.md, docs/home.md, docs/parameters.md, pyproject.toml, src/simmate/command_line/workflows.py, src/simmate/workflow_engine/workflow.py
=> :tulip: allow toml input files

CHANGELOG.md, src/simmate/command_line/test/test_workflows_cli.py, src/simmate/command_line/workflows.py, src/simmate/toolkit/structure_prediction/evolution/workflows/binary_composition.py, src/simmate/toolkit/structure_prediction/evolution/workflows/fixed_composition.py, src/simmate/toolkit/structure_prediction/evolution/workflows/new_individual.py, src/simmate/toolkit/structure_prediction/evolution/workflows/variable_composition.py, src/simmate/workflows/test/test_workflows_utilities.py, src/simmate/workflows/utilities.py
=> :lady_beetle: fix `explore` to accept calc name

src/simmate/calculators/vasp/workflows/electronic_structure/matproj_full.py, src/simmate/database/base_data_types/thermodynamics.py, src/simmate/toolkit/structure_prediction/evolution/database/evolutionary_search.py
=> :gorilla: update binary search outputs

CHANGELOG.md, pyproject.toml, src/simmate/workflow_engine/execution/database.py, src/simmate/workflow_engine/execution/worker.py
=> :bug: fix transaction and release minor

docs/full_guides/database/basic_use.md, docs/full_guides/database/contributing_data.md, docs/full_guides/database/custom_tables.md, docs/full_guides/database/overview.md, docs/full_guides/database/third_party_data.md, docs/full_guides/database/workflow_data.md, docs/full_guides/extras/command_line.md, docs/full_guides/extras/visualization.md, docs/full_guides/extras/visualization/blender.md, docs/full_guides/extras/visualization/overview.md, docs/full_guides/overview.md, docs/full_guides/toolkit.md, docs/full_guides/website/overview.md, docs/full_guides/website/rest_api.md, docs/full_guides/workflows/adding_computational_resources/overview.md, docs/full_guides/workflows/creating_new_workflows.md, docs/full_guides/workflows/third_party_software/bader_henkelman/overview.md, docs/full_guides/workflows/third_party_software/vasp/error_handlers.md, docs/full_guides/workflows/third_party_software/vasp/inputs.md, docs/full_guides/workflows/third_party_software/vasp/installation.md, docs/full_guides/workflows/third_party_software/what_is_a_calculator.md, docs/full_guides/workflows/using_existing_workflows.md, docs/full_guides/workflows/using_prefect.md, docs/full_guides/workflows/workflow_names.md
Fixing typos and improving clarity.
=> Updated documents in the "full_guides" directory

.github/workflows/lint-and-test.yml, docs/getting_started/installation/create_your_env.md, docs/getting_started/installation/quick_start.md, docs/home.md, mkdocs.yml, pyproject.toml, src/simmate/engine/s3_workflow.py
- resolves #333 
- resolves #339
=> add mamba options and deps 🐍 

docs/change_log.md, envs/docker/web_server.dockerfile, src/simmate/engine/workflow.py
=> fix connection close after long flow runs 🐉 

docs/change_log.md, src/simmate/configuration/django/settings.py, src/simmate/database/utilities.py
=> add fix for db reset 🔗 

docs/change_log.md, src/simmate/apps/vasp/inputs/potcar_mappings.py, src/simmate/apps/vasp/outputs/oszicar.py, src/simmate/apps/vasp/workflows/electronic_structure/base_band_structure.py, src/simmate/apps/vasp/workflows/electronic_structure/base_density_of_states.py, src/simmate/apps/vasp/workflows/electronic_structure/utilities.py, src/simmate/database/base_data_types/band_structure.py, src/simmate/database/base_data_types/base.py, src/simmate/database/base_data_types/density_of_states.py, src/simmate/database/base_data_types/relaxation.py
=> add misc vasp fixes 🍉  

docs/change_log.md, src/simmate/engine/workflow.py
=> fix pickling bug ⛏️ 

docs/change_log.md, docs/getting_started/use_a_cloud_database/build_a_postgres_database.md, src/simmate/database/utilities.py
=> fix digital ocean db bug 🦈  

docs/getting_started/example_scripts/overview.md
Updating the documentation for example scripts
=> update examples table 😎 

docs/apps/bader_henkelman/installation.md, docs/apps/bader_henkelman/overview.md, docs/apps/evolution.md, docs/apps/warren_lab/installation.md, docs/apps/warren_lab/overview.md, docs/change_log.md, docs/getting_started/example_scripts/example-001.md, docs/getting_started/example_scripts/example-002.md, docs/getting_started/example_scripts/example_template.md, docs/getting_started/example_scripts/overview.md, mkdocs.yml, pyproject.toml, src/simmate/apps/bader/outputs/acf.py, src/simmate/apps/evolution/models/fixed_composition.py, src/simmate/apps/evolution/workflows/chemical_system.py, src/simmate/apps/vasp/command_line/base_command.py, src/simmate/apps/vasp/command_line/inputs.py, src/simmate/apps/vasp/outputs/vasprun.py, src/simmate/apps/vasp/workflows/diffusion/warren_lab.py, src/simmate/engine/error_handler.py, src/simmate/engine/execution/database.py, src/simmate/engine/test/test_s3_workflow.py
=> fix vasp and evo search bugs

docs/change_log.md, docs/full_guides/workflows/nested_workflows.md, mkdocs.yml, src/simmate/apps/bader/outputs/acf.py, src/simmate/apps/bader/workflows/badelf.py, src/simmate/apps/bader/workflows/bader.py, src/simmate/apps/bader/workflows/combine_chgcars.py, src/simmate/apps/evolution/workflows/new_individual.py, src/simmate/apps/vasp/workflows/electronic_structure/base_band_structure.py, src/simmate/apps/vasp/workflows/electronic_structure/base_density_of_states.py, src/simmate/apps/vasp/workflows/electronic_structure/base_full.py, src/simmate/apps/vasp/workflows/electronic_structure/matproj_band_structure.py, src/simmate/apps/vasp/workflows/electronic_structure/matproj_band_structure_hse.py, src/simmate/apps/vasp/workflows/electronic_structure/matproj_density_of_states.py, src/simmate/apps/vasp/workflows/electronic_structure/matproj_density_of_states_hse.py, src/simmate/apps/vasp/workflows/population_analysis/badelf.py, src/simmate/apps/vasp/workflows/population_analysis/bader.py, src/simmate/apps/vasp/workflows/relaxation/staged.py, src/simmate/apps/vasp/workflows/test/test_band_structure.py, src/simmate/apps/vasp/workflows/test/test_density_of_states.py, src/simmate/command_line/workflows.py, src/simmate/engine/s3_workflow.py, src/simmate/engine/workflow.py, src/simmate/utilities/__init__.py, src/simmate/utilities/files.py, src/simmate/website/workflows/forms.py, src/simmate/workflows/base_flow_types/restart.py, src/simmate/workflows/test/test_workflows_utilities.py, src/simmate/workflows/utilities.py
- fixes #450 
- fixes #451 
- fixes #443
=> standardize prev dir use :eyes: 

docs/change_log.md, pyproject.toml, src/simmate/database/third_parties/utilities.py
=> prep 0.14.0 release :bike: 

src/simmate/website/templates/core_components/site_base.html
updates styling of error messages from django-unicorn
=> add unicorn styling 🦄 

docs/change_log.md, docs/parameters.md, src/simmate/command_line/engine.py, src/simmate/engine/execution/executor.py
=> add utils for pending jobs 🔨 

src/simmate/configuration/django/settings.py
=> add email timeouts ⌚ 

src/simmate/website/core_components/templatetags/getattribute.py
=> fix filter tag getattr 🐛 

docs/change_log.md, src/simmate/database/base_data_types/base.py, src/simmate/database/third_parties/utilities.py, src/simmate/database/utilities.py, src/simmate/engine/workflow.py
=> add db connect decorator 🔌 

src/simmate/apps/evolution/models/fixed_composition.py, src/simmate/apps/evolution/workflows/new_individual.py
=> pass tags in new-ind flows

docs/contributing/maintainer_notes.md, src/simmate/database/third_parties/utilities.py, src/simmate/database/utilities.py, src/simmate/workflows/test/test_all_workflow_runs.py
=> add test suite guide & update prebuilt 📚 

.github/workflows/lint-and-test.yml, docs/change_log.md, docs/getting_started/installation/quick_start.md, docs/home.md, envs/docker/web_server.dockerfile, pyproject.toml
=> remove mamba references 🐍 

.gitattributes
=> add gitattributes config 🧼 

docs/change_log.md, src/simmate/engine/s3_workflow.py
=> fix user given commands 🦋 

envs/conda/dev.yaml, pyproject.toml, src/simmate/apps/badelf/core/badelf.py, src/simmate/apps/evolution/models/fixed_composition.py, src/simmate/apps/vasp/outputs/oszicar.py, src/simmate/database/base_data_types/base.py, src/simmate/database/base_data_types/forces.py, src/simmate/engine/s3_workflow.py, src/simmate/toolkit/creators/utils.py, src/simmate/utilities/files.py
=> update black 🖤 

docs/change_log.md, docs/getting_started/workflows/configure_qe.md, pyproject.toml
=> prep v0.16.1 release

docs/getting_started/workflows/configure_qe.md, docs/getting_started/workflows/quick_start.md
=> add docker install tips 🐳 

.github/workflows/lint-and-test.yml
=> fix macos ci testing 🧀 

src/simmate/apps/warren_lab/workflows/relaxation/hse.py
=> fix spelling typo 🔍 

.github/workflows/lint-and-test.yml
=> patch mac os ci ☕ 

src/simmate/visualization/plotting/plotly_rdkitjs.py, src/simmate/website/core_components/templatetags/simmate_ui_tags.py, src/simmate/website/data_explorer/views.py, src/simmate/website/templates/core_components/site_base.html
=> pin rdkit js 🪛 

docs/change_log.md, pyproject.toml, src/simmate/database/utilities.py
=> prep 0.18.0 release 🚀 

src/simmate/database/base_data_types/base.py, src/simmate/website/core_components/templates/core_components/input_elements/file_upload.html
=> add web queryset hook 🐟 
